#!/usr/bin/env bash
#
# backup the etc directory!
#
cd /home/cskeide/Backup
tar cJPf $(date +%F)-$(hostname)-etc-tar.xz /etc/

# remove older backups
find /home/cskeide/Backup -type f -name '*-etc-tar.xz' -mtime +90 -delete
