#!/bin/bash

# Default AUR helper
aurhelper=/usr/bin/aurman

# Source config file
if [ -e /etc/up.conf ] 
then 
	. /etc/up.conf 
fi

# Upgrade
if [ -e $aurhelper ] || [ -e /usr/bin/$aurhelper ]
then
	if [ $USER == 'root' ]
	then
		pacman -Syu
	else
		echo Using AUR helper $aurhelper
		aurman -Syu
	fi
else 
	echo AUR helper $aurhelper not found - using pacman
	if [ $USER == 'root' ]
	then
		pacman -Syu
	else
		sudo pacman -Syu
	fi
fi
