#!/bin/bash

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID_LIKE
else
    echo Could not find /etc/os-release
    exit 1
fi

if [ "$OS" = "archlinux" ]; then
    exec up-arch
elif [ "$OS" = "debian" ]; then
    exec up-ubuntu
else
    echo Up does not support $OS
fi 
