#!/bin/bash

# Default AUR helper
aurhelper=aurman

# Source config file
[[ -f /etc/up.conf ]] && . /etc/up.conf

cmd=pacman
use_sudo=true

# Upgrade
if hash $aurhelper 2>/dev/null ; then
	cmd=$aurhelper
	use_sudo=false
fi


if [ "$(whoami)" = "root" ] ; then
	cmd=pacman
	use_sudo=false
fi

if [ "$use_sudo" = true ] ; then
	cmd="sudo $cmd"
fi

$cmd -Syu
